name: Deploy React App with Docker Swarm

on:
  push:
    branches:
      - master  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub  # ✅ FIXED LOGIN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.run_id }}

      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker network create --driver overlay react-network || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.run_id }}
            docker service rm react-frontend || true
            docker service create \
              --name react-frontend \
              --publish 3001:80 \
              --network react-network \
              --replicas 1 \
              -e "NODE_ENV=production" \
              ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.run_id }}
