name: Deploy React App with Docker Swarm

on:
  push:
    branches:
      - master  # Deploy when code is pushed to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/react-hello-world:latest .
        docker push $DOCKERHUB_USERNAME/react-hello-world:latest

    - name: Deploy to Docker Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull $DOCKERHUB_USERNAME/react-hello-world:latest
          docker service rm react-hello-world || true
          docker service create \
            --name react-hello-world \
            --publish 3001:80 \
            --replicas 1 \
            $DOCKERHUB_USERNAME/react-hello-world:latest
